name: Hello World

on: 
  push:
    branches:
      - main:
jobs:
  say-hello:
    runs-on: ubunut-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello Neel Dhongde, how are you"
